Chapter 4 Author Review
tidy-survey-r/tidy-survey-book pull request #49
Opened 2023-06-22 00:38 UTC by szimmer

2023-07-08 17:46 UTC, szimmer commented on 04-understanding-survey-data-documentation.Rmd
> +Reviewing both questionnaires and codebooks in parallel is important, as questions and variables are not one-to-one. A single question may have multiple associated variables, or a single variable may
```suggestion
Reviewing both questionnaires and codebooks in parallel is important, as questions and variables do not always correspond directly to each other in a one-to-one mapping. A single question may have multiple associated variables, or a single variable may summarize multiple questions. Reviewing the codebook clarifies how to interpret the variables.
```

2023-07-08 17:46 UTC, szimmer commented on 04-understanding-survey-data-documentation.Rmd
> +For example, if a survey questionnaire contains an error, such as a typo or confusing wording, the researchers would release an erratum that provides a corrected version. Review these corrections bef
```suggestion
For example, if a survey questionnaire contains an error, such as a typo or confusing wording, the researchers would release an erratum that provides a corrected version. Another type of erratum is incorrectly programmed skips in an electronic survey where questions are skipped by the respondent when they should not have been. Review these errata before conducting any analysis to ensure the accuracy and reliability of the survey data and analysis.
```

2023-07-08 17:47 UTC, szimmer commented on 04-understanding-survey-data-documentation.Rmd
> +Missing data can be a significant problem in survey analysis, as it can introduce bias and reduce the representativeness of the data. There are several different types of missing data^[Mack C, Su Z,
Perhaps split these into two categories 1) missing by design (skip patterns) and 2) unintentional missing mechanisms

2023-07-08 17:48 UTC, szimmer commented on 04-understanding-survey-data-documentation.Rmd
> +When running analysis in R, we must missing responses as missing data (i.e., `NA`) and not numeric data. If missing responses are treated as zeros or arbitrary values, they can artificially alter sum
Wording isn't quite right in first sentence. Perhaps ...we must **set** missing responses as missing data...

2023-07-08 17:48 UTC, szimmer commented on 04-understanding-survey-data-documentation.Rmd
> +Suppose our data is not missing completely at random (MCAR). In that case, listwise deletion may produce biased estimates if there is a pattern of respondents who do not respond to specific questions
Add full citation for Allison (2002)

2023-07-08 17:54 UTC, szimmer commented on 04-understanding-survey-data-documentation.Rmd
> +
```suggestion
* Inter-university Consortium for Political and Social Research (ICPSR) - [https://www.icpsr.umich.edu/web/pages/]
* American Community Survey (ACS) - [https://www.census.gov/programs-surveys/acs/microdata.html]
```

2023-07-10 00:47 UTC, rpowell22 commented on 04-understanding-survey-data-documentation.Rmd
>  library(tidyverse)
Let's add a set up section where we pull all this in.

2023-07-10 01:26 UTC, rpowell22 requested changes

2023-07-10 01:26 UTC, rpowell22 commented on 04-understanding-survey-data-documentation.Rmd
> +Before diving into survey analysis, it's crucial to review the survey documentation thoroughly. This documentation includes technical guides, questionnaires, codebooks, errata, and other useful resou
```suggestion
Before diving into survey analysis, it's crucial to review the survey documentation thoroughly. This documentation includes technical guides, questionnaires, codebooks, errata, and other useful resources. By taking the time to review these materials, we can gain a comprehensive understanding of the survey data (including research and design decisions discussed in Chapters \@ref(c02-overview-surveys) and \@ref(c03-specifying-sample-designs)) and effectively conduct our analysis. 
```

2023-07-10 01:26 UTC, rpowell22 commented on 04-understanding-survey-data-documentation.Rmd
> +Below in Figure \@ref(fig:que-examp), we show a question from the ANES 2020 questionnaire. This figure shows a particular question's question name (`postvote_rvote`), description (Did R Vote?), full
Need a citation for where the example comes from.

2023-07-10 01:26 UTC, rpowell22 commented on 04-understanding-survey-data-documentation.Rmd
> +The content and structure of questionnaires vary depending on the specific survey. For instance, question names may be informative (like the ANES example), sequential, or denoted by a code.  In some
Need citation for BRFSS example.

2023-07-10 01:26 UTC, rpowell22 commented on 04-understanding-survey-data-documentation.Rmd
> +Given the variety in documentation, it is essential to consider the specific survey when interpreting the information presented in a questionnaire.
I'm not sure what this sentence is getting at.

2023-07-10 01:26 UTC, rpowell22 commented on 04-understanding-survey-data-documentation.Rmd
> +Figure \@ref(fig:codebook-examp) is a question from the ANES 2020 codebook. This part indicates a particular variable's name (`V202066`), question wording, value labels, universe, and associated surv
Again, cite for ANES.

2023-07-10 01:26 UTC, rpowell22 commented on 04-understanding-survey-data-documentation.Rmd
> +The survey documentation, often the codebook, represents the missing data with a code. For example, a survey may have "Yes" responses coded to `1`, "No" responses coded to `2`, and missing responses
We don't need to repeat the same codebook example.  Just use the figure # to reference back to the first one.

2023-07-10 01:26 UTC, rpowell22 commented on 04-understanding-survey-data-documentation.Rmd
> +### Accounting for MCAR, MAR, and MNAR missingness
Do we want to spell these out in headers?  I did with BRR in ch3.

2023-07-10 01:26 UTC, rpowell22 commented on 04-understanding-survey-data-documentation.Rmd
> +#| label: drop-na-example
Should we display dat before we filter just so people can easier see the differences?

2023-07-10 01:26 UTC, rpowell22 commented on 04-understanding-survey-data-documentation.Rmd
> +Let's look at the survey documentation for the American National Election Studies (ANES) 2020. The survey website is located at [https://electionstudies.org/data-center/2020-time-series-study/](https
Let's add a formal citation to this as well

2023-07-10 01:26 UTC, rpowell22 commented on 04-understanding-survey-data-documentation.Rmd
> +As mentioned above, we want to conduct ANES data analysis with weights to accurately represent the population. The user guide references a supplemental document called "How to Analyze ANES Survey Dat
There is a bit of a cognitive jump to get to this paragraph.  We should really walk people through step by step and provide as much information as we can about this.  We don't talk ANES weights summing to the sample and why we would want to sum to the population.  We should provide this detail.

2023-07-10 01:26 UTC, rpowell22 commented on 04-understanding-survey-data-documentation.Rmd
> +We will use Current Population Survey (CPS) to find a number of the non-institutional U.S. citizens aged 18 or older living in the 50 U.S. states or D.C. The {censusapi} package allows us to run a re
We use tidycensus in ch3, can we not use that here as well?

2023-07-10 01:26 UTC, rpowell22 commented on 04-understanding-survey-data-documentation.Rmd
> +  vars = c("HRHHID", "HRMONTH", "HRYEAR4", "PRTAGE", "PRCITSHP", "PWSSWGT"),
We should provide some explanation as to what the variables are that we're pulling out and why they matter.

2023-07-10 01:26 UTC, rpowell22 commented on 04-understanding-survey-data-documentation.Rmd
> +         PRCITSHP %in% (1:4)) %>%
We should provide detail to the reader why we're doing this and what it represents.

2023-07-10 01:26 UTC, rpowell22 commented on 04-understanding-survey-data-documentation.Rmd
> +The target population in 2020 is `r scales::comma(targetpop)`. This information gives us what we need to create the post-election survey object with {srvyr}.
We should explain a bit more about what the target population is and walk through each of the analysis steps to get there.  OR we could just go to the CPS page and pull up the # and just cite it.  May be eaiser?

2023-07-10 01:26 UTC, rpowell22 commented on 04-understanding-survey-data-documentation.Rmd
> +  mutate(Weight = V200010b / sum(V200010b) * targetpop)
As I mentioned above, we need to explain why we do this.  We don't have this anywhere else.

2023-07-10 01:26 UTC, rpowell22 commented on 04-understanding-survey-data-documentation.Rmd
> +## Searching for public-use survey data
I'm not really a fan of this section.  I feel like there are two things conflated here: the data we use in the book, and where people can find data.

If we want to go where people find data then let's structure this differently such as:
- Many governments have publicly available data.  For example, in the U.S. you can get data directly from the various statistical agencies such as the Census Bureau or the CDC.  Or in the UK you can get data directly from the Office for National Statistics.
- There are also data repositories like ICPSR, Odum, others???
- Other websites have compiled a list of free data such as asdfree, others??

2023-08-06 20:56 UTC, merged